pipeline {
    agent {
        label 'master'
    }
    stages {
        stage('Build') {
            steps {
                bat "C:\\\"Program Files\"\\apache-maven-3.9.4\\bin\\mvn -B -DskipTests clean package"
            }
        }
        stage('Test') {
            steps {
                bat  "C:\\\"Program Files\"\\apache-maven-3.9.4\\bin\\mvn test"
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo 'Nothing'
             //   sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
